language: node_js
sudo: false
node_js:
  - "8.10"
cache: npm
branches:
  only:
    - master
install:
  - npm install
  - lerna exec npm install
  - lerna link
jobs:
  include:
    - stage: release
      if: branch = "master" AND type = "push"
      script: lerna publish --skip-npm