language: node_js
sudo: false
node_js:
  - "8.10"
cache: npm
branches:
  only:
    - master
before_install:
  - git checkout master
install:
  - npm ci
  - lerna exec npm ci
  - lerna link
jobs:
  include:
    - stage: release
      if: branch = "master" AND type = "push"
      #script: lerna publish --skip-npm
      script: lerna version