language: node_js
sudo: false
node_js:
  - '8.10'
cache: npm
branches:
  only:
    - master
before_install:
  - npm install -g npm
install:
  - echo "> Before change"
  - cat .git/config
  - git remote add origin https://Pavel910:[GH_TOKEN]@github.com/Pavel910/lerna-monorepo.git
  - echo "> After change"
  - cat .git/config
  - git checkout master
  - npm ci
  - lerna exec npm ci
  - lerna link
jobs:
  include:
    - stage: release
      if: branch = "master" AND type = "push"
      script: lerna version -y
